services:
  pygeoapi:
    image: 52north/directed-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config.yml:/pygeoapi/local.config.yml
    ports:
      - "5000:80"
